#!/usr/bin/env python3
"""Shared geometry and .obj emit for the generated placeholder hulls.

Placeholder assets are generated from a script wherever that is practical, so an
asset review is a diff review and nothing needs a DCC tool to reproduce (ADR
0030). Real art replaces the .obj in place; nothing in code knows it was
generated.

Godot convention: -Z is forward, +Y is up. Every part is a convex solid; face
winding is fixed up automatically against the part's own centroid, so the part
definitions do not have to get vertex order right by hand.
"""


# --- tiny vector helpers -----------------------------------------------------

def add(a, b): return (a[0] + b[0], a[1] + b[1], a[2] + b[2])
def sub(a, b): return (a[0] - b[0], a[1] - b[1], a[2] - b[2])
def dot(a, b): return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]
def scale(a, k): return (a[0] * k, a[1] * k, a[2] * k)


def cross(a, b):
    return (a[1] * b[2] - a[2] * b[1], a[2] * b[0] - a[0] * b[2], a[0] * b[1] - a[1] * b[0])


def normalize(v):
    m = (v[0] ** 2 + v[1] ** 2 + v[2] ** 2) ** 0.5
    return (0.0, 1.0, 0.0) if m < 1e-9 else (v[0] / m, v[1] / m, v[2] / m)


def centroid(points):
    n = len(points)
    return (sum(p[0] for p in points) / n, sum(p[1] for p in points) / n, sum(p[2] for p in points) / n)


# --- part builders -----------------------------------------------------------

class Part:
    """A convex solid: a vertex list plus faces as index tuples."""

    def __init__(self, verts, faces):
        self.verts = [tuple(map(float, v)) for v in verts]
        self.faces = [list(f) for f in faces]
        self._orient()

    def _orient(self):
        """Flip any face whose normal points inward. Convexity makes this exact."""
        c = centroid(self.verts)
        for face in self.faces:
            pts = [self.verts[i] for i in face]
            n = cross(sub(pts[1], pts[0]), sub(pts[2], pts[0]))
            if dot(n, sub(centroid(pts), c)) < 0.0:
                face.reverse()


def prism(polygon, offset):
    """Extrude an ordered planar polygon by `offset`. Winding is fixed afterwards."""
    n = len(polygon)
    verts = list(polygon) + [add(p, offset) for p in polygon]
    faces = [list(range(n)), list(range(n, 2 * n))]
    for i in range(n):
        j = (i + 1) % n
        faces.append([i, j, j + n, i + n])
    return Part(verts, faces)


def box(center, size):
    hx, hy, hz = size[0] / 2, size[1] / 2, size[2] / 2
    v = [(center[0] + sx * hx, center[1] + sy * hy, center[2] + sz * hz)
         for sx in (-1, 1) for sy in (-1, 1) for sz in (-1, 1)]
    faces = [[0, 1, 3, 2], [4, 5, 7, 6], [0, 1, 5, 4], [2, 3, 7, 6], [0, 2, 6, 4], [1, 3, 7, 5]]
    return Part(v, faces)


def ring(z, half_width, top, bottom):
    """A hexagonal cross-section at station `z`. Faceted rather than round: the
    hull is meant to read as cut crystal, not as a tube."""
    return [
        (0.0, top, z),
        (half_width, top * 0.25, z),
        (half_width * 0.72, -bottom, z),
        (0.0, -bottom * 1.12, z),
        (-half_width * 0.72, -bottom, z),
        (-half_width, top * 0.25, z),
    ]


def frustum(ring_a, ring_b):
    """Close two equal-length rings into a convex solid. Built one segment at a
    time rather than as one long hull, because `Part` fixes winding against the
    part's own centroid and that is only exact for a convex solid."""
    n = len(ring_a)
    verts = list(ring_a) + list(ring_b)
    faces = [list(range(n)), list(range(n, 2 * n))]
    for i in range(n):
        j = (i + 1) % n
        faces.append([i, j, j + n, i + n])
    return Part(verts, faces)


def cone(ring_verts, apex):
    """Close a ring onto a single point."""
    n = len(ring_verts)
    verts = list(ring_verts) + [apex]
    faces = [list(range(n))] + [[i, (i + 1) % n, n] for i in range(n)]
    return Part(verts, faces)


def mirror_x(part):
    verts = [(-v[0], v[1], v[2]) for v in part.verts]
    return Part(verts, [list(f) for f in part.faces])


# --- obj emit ----------------------------------------------------------------

def planar_uv(p, n, uv_scale):
    """Project onto whichever axis plane the face most faces. Good enough for a
    panel texture on a gray-box hull, and it needs no unwrap step."""
    ax, ay, az = abs(n[0]), abs(n[1]), abs(n[2])
    if ax >= ay and ax >= az:
        u, v = p[2], p[1]
    elif ay >= az:
        u, v = p[0], p[2]
    else:
        u, v = p[0], p[1]
    return (u * uv_scale + 0.5, 1.0 - (v * uv_scale + 0.5))


def write_obj(out_path, object_name, parts, generator, uv_scale=0.35):
    lines = [
        "# %s.obj — gray-box hull for Missile Rider." % object_name,
        "# GENERATED by tools/%s. Do not hand-edit; edit the generator." % generator,
        "o %s" % object_name,
    ]
    positions, uvs, normals, face_rows = [], [], [], []

    for part in parts:
        base = len(positions)
        positions.extend(part.verts)
        for face in part.faces:
            pts = [part.verts[i] for i in face]
            n = normalize(cross(sub(pts[1], pts[0]), sub(pts[2], pts[0])))
            normals.append(n)
            ni = len(normals)
            corners = []
            for idx, p in zip(face, pts):
                uvs.append(planar_uv(p, n, uv_scale))
                corners.append("%d/%d/%d" % (base + idx + 1, len(uvs), ni))
            face_rows.append("f " + " ".join(corners))

    lines += ["v %.4f %.4f %.4f" % p for p in positions]
    lines += ["vt %.4f %.4f" % uv for uv in uvs]
    lines += ["vn %.4f %.4f %.4f" % nn for nn in normals]
    lines += face_rows

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n")
    tris = sum(len(r.split()) - 3 for r in face_rows)
    extent = tuple(max(abs(p[i]) for p in positions) for i in range(3))
    print("wrote %s — %d verts, %d faces, %d tris, extent +-(%.1f, %.1f, %.1f)"
          % (out_path, len(positions), len(face_rows), tris, *extent))
